### ISSUE TITLE
How drones keep track of previously received flood_ids?

### ISSUE THREAD

**Issue by StefanoGirardi** [WGL-2024/WGL_repo_2024#101]
I don't know if for everyone is clear, for me clearly not, but how drones keep track of previously received flood_ids? So I might have missed how they do since in DroneOptions we don't have any fields to store received flood_ids. I don't know if it was said previously that every drone must have, for example a field: flood_ids: Vec<u64> or not. Please if anyone can clarify on this matter assuming that the current AP_protocol.md is updated on this. Thanks

**Comment by DiCesareDaniele** [comment]
You are free to implement that as you wish, but I would suggest using an HashSet.

Btw you can add fields in your drone that are not part of DroneOptions. Those are just for initialization
