### ISSUE TITLE
Crash and Nack a.k.a. Crack

### ISSUE THREAD

**Issue by DiCesareDaniele** [WGL-2024/WGL_repo_2024#110]
This is a grouping of all the proposed ways to handle drones crashing.

# Overview
The problem is that the protocol is yet to define some edge cases when a drone crashes. This leads to `Fragments` getting lost in the network without `Nack` getting produced, or the loss of `Nacks`.

## Issue 1
A `Drone` receives a `Crash` with packets in its buffer. The implied behavior until now was that the `Drone` crashes as soon as it receives the command and the `Packets` get dropped without producing a `Nack`, and if there were `Nacks` in those `Packets`, they would also get dropped without receiving the destination, which is against the rules of the main.

### 1
Close the channels and forward all the packets before actually crashing.

**Pros**:
- simple

**Cons**:
- the Drone does not crash when told to

### 2
Close the channels and drop all the packets before actually crashing (#108).

**Pros**:
- simple
- immediatly updates the network

**Cons**:
- the Drone does not crash when told to
- lot of Nacks

### 3
Removing `Nacks` and adding timers instead (#84). This might seem like an overcomplication at first, but considering how hard it is to ensure that a `Nack` receives the destination, it's not that dumb.

**Pros**:
- realistic

**Cons**:
- might be hard
- might be against the main

## Issue 2
A drone crashes in the middle of the route of a Nack.

**Example**:
```mermaid
flowchart LR;
D1(D1);
D2(D2);
D3(D3);
C1 <--> D1;
C1 <--> D2;
D1 <--> D3;
D2 <--> D3;
D3 <--> S1;
```
C1 wants to send a `Packet` to S1 (path: [C1, D1, D3, S1])
The `Packet` gets dropped at D3 so D3 is going to sends a `Nack` back at C1 (path: [D3, D1, C1]).
> If an error occurs, then a Nack is sent.
Source Routing Header contains the path to the client, which can be obtained by reversing the list of hops contained in the Source Routing Header of the problematic Message.

Meanwhile D1 receved a command from the controller to `Crash`. The `Packet` cannot arrive at C1 and the `Drone` cannot find another route since `Drones` do not keep routing tables, even tho the path exists.
> Clients and servers use source routing: the path that a packet takes through the drone network is determined by the client and server themselves instead of routers. The consequence is that drones do not maintain routing tables.

This would imply that the `Nack` won't be able to receive the destination, which is against the rules of the main, and it cannot be sent back since we cannot produce a `Nack` for a `Nack`. 

### 1
Remove Nacks and pass through the controller instead (#64).

**Pros**:
- super simple

**Cons**:
- not realistic

### 2
Pass through the controller only if the drone crashed (#109). 

**Pros**:
- simple

**Cons**:
- like 1 but we use the controller only if forced to

### 3
Keep the thread idle and just forward Nacks and Acks.

**Pros**:
- simple

**Cons**:
- we never clean memory
- channels do not get closed so drones still see the drone as a neighbor

### 4
Broadcast the Nack.

**Pros**:
- realistic

**Cons**:
- network overloaded

### 4
Removing Nacks and add timers instead (#84). Just like Issue 1.

**Pros**:
- realistic

**Cons**:
- might be hard
- might be against the main

**Comment by DiCesareDaniele** [comment]
> #84 doesn't say anything about removing nacks, I assumed that we would keep them along adding timeouts

Why would we need Nacks if we have timeouts

**Comment by matteo-dinoia** [comment]
Let's merge all the voted change about crashing node in a single PR.

**Comment by DiCesareDaniele** [comment]
The changes voted during the WG were option 2 (#108) for Issue 1 and option 2 (#109) for Issue 2

**Comment by DiCesareDaniele** [comment]
After those get merged I'll proced to close this

**Comment by matteo-dinoia** [comment]
Closing because the PR is practically ready, just cosmetic changes and we will merge it
