### ISSUE TITLE
Server type

### ISSUE THREAD

**Issue by daw-dev** [WGL-2024/WGL_repo_2024#43]
We're not sure about something for initialization and flooding: in general, how can a client know the type of a particular server? Is it implied by the node id itself, is it included in the flood information or does the client need to ask for the type with a special kind of message?

**Comment by matteo-dinoia** [comment]
There is a message for asking that to a server

**Comment by matteo-dinoia** [comment]
Closing the issue. If you feel that it's still not clear, you can msg me on telegram or reopen the issue.
