### ISSUE TITLE
Config structs don't use NodeId

### ISSUE THREAD

**Issue by ZGako** [WGL-2024/WGL_repo_2024#46]
I noticed that in the latest merges, we changed NodeId from u64 to u8. Which I guess is fine. But the structs in the config files weren't updated.
When you try to import them, you'll have to deal with conversions. 
I believe this can be fixed without a vote or anything since it's still in the scope of the "From executable to library" PR.

**Comment by matteo-dinoia** [comment]
Sure open a PR for that.
Issue are for other things that should be discussed but there is no implementation yet.
