### ISSUE TITLE
Ambiguous terms in Fragment Reassembly

### ISSUE THREAD

**Issue by Isax03** [WGL-2024/WGL_repo_2024#59]
In the Fragment Reassembly paragraph there is the terms `file_size` and `file` and it is the only place where I found them.
I think they are namely `length: u8` and `data: [u8; 80]` attributes of the `struct Fragment` but I am not sure.

Below there is the cited paragraph.

> ```rust
> // OTHER CODE
> pub struct Fragment {
>	 fragment_index: u64,
>	 total_n_fragments: u64,
>	 length: u8,
>	 // assembler will fragment/defragment data into bytes.
> 	data: [u8; 80] // usable for image with .into_bytes()
> }
> ```
>
>  To reassemble fragments into a single packet, a client or server uses the fragment header as follows:
> 1. The client or server receives a fragment.
> 2. It first checks the `session_id` in the header.
> 3. If it has not received a fragment with the same `session_id`, then it creates a vector big enough where to copy the data of the fragments.
> 4. The client would need to create a `vec<u8>` with capacity of `total_n_fragments` * 80.
> 5.  It would then copy `file_size` elements of the `file` array at the correct offset in the vector.
> Note that, if there are more than one fragment, `file_size` must be 80 for all fragments except for the last.

**Comment by matteo-dinoia** [comment]
file size should be total number of fragment.
The element of the file, should be the data of the fragment.

If you want to clarify this please do in a PR.
