### ISSUE TITLE
 🔴 Dynamic data in Packet

### ISSUE THREAD

**Issue by DiCesareDaniele** [WGL-2024/WGL_repo_2024#63]
## 🔴 Dynamic data in Packet
Packet contains dynamic size data (like SourceRoutingHeader) but the project main states that this is not possible: 
> As anticipated in the description, when a client (respectively, a server) sends a message to a server (respectively, a client), the message is serialized and fragmented if it exceeds a certain size and reassembled at the destination.
Serialization means converting a packet containing dynamically-sized data structures to one containing fixed-sized arrays instead.

Note that I would very much prefer if we could just throw a Vec in there but unlike the protocol the main document cannot be changed

### Proposal
Go back to fixed size array (as it was before). This has the downside that the source routing header might not fit in the Packet. I have no good solution at the moment for this. Perhaps we can discuss about this the next WG. 

If you have any ideas please share them in a comment <3

**Comment by matteo-dinoia** [comment]
I asked the professor. It is fine as long is not in the message dat. SourceRoutingHeader can be a vector.

**Comment by matteo-dinoia** [comment]
Closing. if you think there is more to say please reopen it.
