### ISSUE TITLE
🟡 Simulation Controller unclear

### ISSUE THREAD

**Issue by DiCesareDaniele** [WGL-2024/WGL_repo_2024#65]
## 🟡 Simulation Controller unclear
The protocol states:
> The Simulation Controller can send the following commands to drones:
>
> ...
>
> `Spawn(id, code)`: This command adds a new drone to the network.
>
> `SetPacketDropRate(id, new_pdr)`: 

> The Simulation Controller can receive the following events from nodes:
>
> `Topology(node_id, list_of_connected_ids, metadata)`: This event indicates that node  `node_id`  has been added to the network and its current neighbors are  `list_of_connected_ids`. It can carry metadata that could be useful to display, such as the PDR and DR of Drones.
>
> `MessageSent(node_src, node_trg, metadata)`: This event indicates that node  `node_src`  has sent a message to  `node_trg`. It can carry useful metadata that could be useful display, such as the kind of message, that would allow debugging what is going on in the network.

These are the part that I found problematic
- `Spawn`: does not make sense it's not a command that a drone receive it just receive AddSender to add that drone as it's neighbour
- `SetPacketDropRate`: missing in wg_2024::controller::Command
- `Topology`: again this is not something that the nodes should do. It should be the controller to keep track of the Topology
- `MessageSent`: missing in wg_2024::controller::Command

Also I would separate Command in DroneCommand and ControllerCommand
- `DroneCommand`: commands sent from the controller to the drone
- `ControllerCommand`: commands sent from the drone to the controller

This would also imply that DroneOptions would take
sim_contr_send: Sender\<ControllerCommand\>
sim_contr_recv: Receiver\<DroneCommand\>
Instead of
sim_contr_send: Sender\<Command\>
sim_contr_recv: Receiver\<Command\>

### Proposal
I will do a PR with the fixes later this week when I'll find some free time. Not the night before the WG I swear ;). I have opened this issue to gather your feedback if you think this could be a useful change

**Comment by matteo-dinoia** [comment]
I agree with the split of Command. Also i agree the initialization command are useless for how we did our initialization.

When you do the PR i'll gladly look at it.

**Comment by luiss07** [comment]
I already have something ready. I'm planning on making the PR later this evening. My idea was to keep only the `Command` to avoid having a lot of different channels and just specify which command is used for what. If you still prefer to propose splitting them, you could start from mine.

**Comment by DiCesareDaniele** [comment]
> I already have something ready. I'm planning on making the PR later this evening. My idea was to keep only the `Command` to avoid having a lot of different channels and just specify which command is used for what. If you still prefer to propose splitting them, you could start from mine.

I'll look at your PR before opening mine. But I would keep them separate cause it does not make sense that the controller receave AddChannel for example

**Comment by Suge42** [comment]
About the 'spawn' and 'topology' command, they're commands that we users can use in the Simulation Controller, that part of the protocol isn't described as our implementation of the drones.
These are more the buttons we press on the UI rather than what the code actually do.
About the channels we would need to discuss if we prefer to double the channels, or use them inside a Command enum.

**Comment by DiCesareDaniele** [comment]
> About the 'spawn' and 'topology' command, they're commands that we users can use in the Simulation Controller, that part of the protocol isn't described as our implementation of the drones. These are more the buttons we press on the UI rather than what the code actually do. About the channels we would need to discuss if we prefer to double the channels, or use them inside a Command enum.

Yeah yeah I know but they are under: The simulation controller can send/receive the following command
That is what I found confusing

**Comment by matteo-dinoia** [comment]
Relative to issue 1 it has no advantage to it

To have the advantage you are talking about SC trait should INSTEAD contains:
new(...)
start()
similarly to drones.

**Comment by marcoff181** [comment]
> Relative to issue 1 it has no advantage to it
> 
> To have the advantage you are talking about SC trait should INSTEAD contains: `new(...) start()` similarly to drones.
> 
> Relative about issue 2: yes we would need that if we implement the new and start/run trait.

Yes, I was already thinking that if we kept it we would at least implement those traits because otherwise I don't see any use in defining it in the first place

**Comment by matteo-dinoia** [comment]
No what i mean is thar even if we add NEW and RUN, the other function CRASH,...will be useless unless we want to force the split between  backend and frontend using this struct. But i see no gain to do so.

**Comment by matteo-dinoia** [comment]
> No what i mean is thar even if we add NEW and RUN, the other function CRASH,...will be useless unless we want to force the split between  backend and frontend using this struct. But i see no gain to do so.

Or do you need only new and run?

**Comment by marcoff181** [comment]
No, you are right, I was thinking about only using new and run, because as you say there is no reason to have the other functions when you have those two and you have defined the commands
