### ISSUE TITLE
Simulation Events

### ISSUE THREAD

**Issue by daw-dev** [WGL-2024/WGL_repo_2024#77]
For now we only discussed about `SimulationCommand`s, but the project files also talk about `SimulationEvent`s, so for example when a drone forwards a packet or when a server sends a respond and so on. I think we should discuss them and make them clear.

**Comment by luiss07** [comment]
Imo SimulationCommands can be intended as SimulationEvents. If you check the PR I did about Simulation commands, the nodes can use the command SentPacket to tell the SC that they sent a package (same for DroppedPacket). That can be considered as an event.

**Comment by daw-dev** [comment]
I was referring with Events the ones from nodes to the simulation controller and with Commands the other way around. I think the separation in cleaner and cooler. But we can discuss this (this is why I created an issue)

**Comment by daw-dev** [comment]
We could even create a trait like "ControllerMessage" so that every group can do as they want

**Comment by DiCesareDaniele** [comment]
> I was referring with Events the ones from nodes to the simulation controller and with Commands the other way around. I think the separation (for example using two different enums) in cleaner and cooler. But we can discuss this (this is why I created an issue)

Yeah I also thought about separating them. The idea was to call them ControllerCommand and DroneCommand

**Comment by daw-dev** [comment]
I prefer Events because Drones are not giving Commands to the Simulation Controller, they're just notifing that something happened, this is why I like Events. Anyway, it's just naming.

**Comment by luiss07** [comment]
> > I was referring with Events the ones from nodes to the simulation controller and with Commands the other way around. I think the separation (for example using two different enums) in cleaner and cooler. But we can discuss this (this is why I created an issue)
> 
> Yeah I also thought about separating them. The idea was to call them ControllerCommand and DroneCommand

The thing is that not only Drones can trigger the command/event of a packet sent, but also Clients and Servers. By splitting the enum we'd solve the ambiguity of what is a command and what an event (from SC or from Nodes), but we'd not remove the ambiguity of having some commands/events that can be sent/received to/from all Nodes or only Drones. 

In the end, we'd have to manage an additional channel and still have some ambiguity. I do get your point, I really can't see all these advantages.

My idea, just to involve all the WG, would be to vote on the PR, and if approved we can directly vote on whether to split the commands (into: from SC (commands) and from Nodes (events)) or not.

Anyway, the PR is still marked as not ready, thus I don't know if we will vote on it on monday.

**Comment by matteo-dinoia** [comment]
I don't think server or client need a channel to send to the simulation controller. And depending of what we choose, we may not even create a channel from SC to server/client. 

Or am i wrong? Feel free to correct me

**Comment by luiss07** [comment]
If we don't create the channel from the SC to the server/client then we would only know the packets exchange between drones and not when a server/client sends the packet. Which means missing information

**Comment by marcoff181** [comment]
I think that only drones can crash (and if that's not clear in the protocol we should specify it), but we need the channel with Server/Client for knowing when they send packets

**Comment by luiss07** [comment]
By giving a fast read (CTRL+F) to the main file, you may be right and only drones can crash (you might want to double-check it, given the time😂). 

If that's the case I need to change my PR and put that only drones can crash. Which will make our lives easier.

**Comment by matteo-dinoia** [comment]
> I think that only drones can crash (and if that's not clear in the protocol we should specify it), but we need the channel with Server/Client for knowing when they send packets

But do we need them tho? Like it will reach a node surely.

**Comment by marcoff181** [comment]
I don't think you can say that it's truly needed but at the same time if the simulation controller can keep track of which messages a drone is sending/has dropped, it would be weird to not have that functionality also for Server and Client.

You can also display more high level information about the Server and Client, because, for example they could send a Command to the Simulation Controller saying that they have requested a file/image

And also, now that I think about it, Clients don't decide by themselves to send request to Servers, right? Which means that The SimulationController sends them a Message telling them that they should perform an action, or do Clients just randomly do some Requests?

**Comment by matteo-dinoia** [comment]
I thinkwe decide what the client do.  By for example clicking send on a message in the client application

**Comment by daw-dev** [comment]
No, (at least as I understood it) the UI with everything is in the simulation controller. I imagine you would click on the client, a window would pop up, then a list of all the requests that it can make and you can select one. So since it's all in the simulation controller we need a command for it. I think this is clear in the project main, I'll check.

**Comment by marcoff181** [comment]
> No, (at least as I understood it) the UI with everything is in the simulation controller. I imagine you would click on the client, a window would pop up, then a list of all the requests that it can make and you can select one. So since it's all in the simulation controller we need a command for it. I think this is clear in the project main, I'll check.

I also think that's how it  is meant to be, which means we need to define a third set of commands with these interactions

**Comment by matteo-dinoia** [comment]
> No, (at least as I understood it) the UI with everything is in the simulation controller. I imagine you would click on the client, a window would pop up, then a list of all the requests that it can make and you can select one. So since it's all in the simulation controller we need a command for it. I think this is clear in the project main, I'll check.

I think this is the kind of thing we should ask the professor because i remember him saying that the client could implement UI

**Comment by marcoff181** [comment]
Another thing to vote on😂 One thing is that if Client/Server implementors need to also set up some kind of UI on top of the rest of the requirements, the individual contributions end up pretty unbalanced, with Simulation Controller being quite easier to implement than the rest

**Comment by daw-dev** [comment]
That's why I think Clients and Servers just respond to commands like `SendRequest(Request)`. All the UI stuff should be in the SimulationController.
Maybe a cool thing could be to separate stuff into `DroneCommand`s (as in commands for drones), `DroneEvent`s (as in events raised by drones), `HostCommand`s (as in commands for hosts), `HostEvent`s (as in events raised by hosts) so that the first two are to be discussed with the working group, while the others can be a small group thing.

**Comment by luiss07** [comment]
> Another thing to vote on😂 One thing is that if Client/Server implementors need to also set up some kind of UI on top of the rest of the requirements, the individual contributions end up pretty unbalanced, with Simulation Controller being quite easier to implement than the rest

I don't think there is a need to vote on it. Client/Server are personal contributions, thus it will be up to the group to decide what to do.

**Comment by matteo-dinoia** [comment]
> Another thing to vote on😂 One thing is that if Client/Server implementors need to also set up some kind of UI on top of the rest of the requirements, the individual contributions end up pretty unbalanced, with Simulation Controller being quite easier to implement than the rest

I believe that the server is stupidly easy to implement and simulation controller is probably the hardest

**Comment by matteo-dinoia** [comment]
> > Another thing to vote on😂 One thing is that if Client/Server implementors need to also set up some kind of UI on top of the rest of the requirements, the individual contributions end up pretty unbalanced, with Simulation Controller being quite easier to implement than the rest
> 
> I don't think there is a need to vote on it. Client/Server are personal contributions, thus it will be up to the group to decide what to do.

Partially, we can impose restriction if we want.

**Comment by marcoff181** [comment]
Now that I think more about it,maybe it does make the simulation controller more difficult in respect to the others. If we decide that we want the client to be interchangeable between groups we can say in the protocol that the client needs to implement some kind of interface to sends commands

**Comment by DiCesareDaniele** [comment]
> For now we only discussed about `SimulationCommand`s, but the project files also talk about `SimulationEvent`s, so for example when a drone forwards a packet or when a server sends a respond and so on. I think we should discuss them and make them clear.

Watch #79

**Comment by daw-dev** [comment]
Solved in #79
