### ISSUE TITLE
Ack!? What the fAck

### ISSUE THREAD

**Issue by DiCesareDaniele** [WGL-2024/WGL_repo_2024#82]
The protocol states: 
> If a drone receives a Message and can forward it to the next hop, it also sends an Ack to the client.

First of all: drones do not receive Messages, but Packets.

Second, why does the drone send an Ack on each Packet received? Shouldn't acks get send only by client/server (last hop) and then be forwarded by drones? Have we understood wrong or is it an error?

**Comment by matteo-dinoia** [comment]
Is this in our protocol or in the part we cannot change?

I agree this should clearly be client/server

**Comment by daw-dev** [comment]
I thought it was just the professor way to spice things up

**Comment by Suge42** [comment]
So this was solved with a PR? In that case I would close the issue, or label it as 'not to vote' and leave it there just because I find the name funny.

**Comment by DiCesareDaniele** [comment]
Since #102 has the ready for merge label I'll close this
