### ISSUE TITLE
Bounded or Unbounded?

### ISSUE THREAD

**Issue by marcoff181** [WGL-2024/WGL_repo_2024#88]
I can't find anywhere in the protocol that states if we use bounded or unbounded channels, but the example uses unbounded, is there any agreement on this?

**Comment by matteo-dinoia** [comment]
There is no agreement. 

I believe an unbounded channel is best.

**Comment by matteo-dinoia** [comment]
Unbound 0 is more than excessive and will cause complication. 

But yeah while the type is interchangable we should still decide because drone thought with unbounded or bounded could not work (probably won't work) while using the other type of channel.

I believe unbounded are the most flexible and easy for us.

**Comment by lillo24** [comment]
From what done so far I don't see any restrictions on any bound on tne amount of data through a channel, so I guess unbounded makes sense and it is easier to implement, why not.
(especially If memory usage is not a concern)

**Comment by marcoff181** [comment]
If we are sure that a drone that has been developed and tested by a group, using unbounded channels, can be used without any problem with bounded channels and the opposite is true, then there is no problem in keeping them both.

Even knowing that they both return `Sender` I was worried that there could still be a case where drone logic meant for unbounded would cause different behavior with bounded, but I can't think of any at the moment.

**Comment by DiCesareDaniele** [comment]
> If we are sure that a drone that has been developed and tested by a group, using unbounded channels, can be used without any problem with bounded channels and the opposite is true, then there is no problem in keeping them both.
> 
> Even knowing that they both return `Sender` I was worried that there could still be a case where drone logic meant for unbounded would cause different behavior with bounded, but I can't think of any at the moment.

The Sender/Receiver of unbounded are the same type of bounded. Thus one cannot write an implementation that works for one but not the other (assuming that the buffer has enough space). Also you do not create the channels in the drone but they are passed as argument, so it is not the drone that choses to use bounded/unbounded but the network initializer which is internal.

Hope this clarifies any doubts, and I think with this we can close the issue

**Comment by DiCesareDaniele** [comment]
Since this is a group defined part and we proposed a way to solve the problem please close this issue to not cloug up the Issues tab

**Comment by matteo-dinoia** [comment]
I do believe there is still to talk about this. I think not defining this could cause some drone to behave differntly based on which type of channel we use.

**Comment by DiCesareDaniele** [comment]
> I do believe there is still to talk about this. I think not defining this could cause some drone to behave differntly based on which type of channel we use.

As I said before the only difference is that with bounded send might block if there is not enough space in the buffer, so it's likely better to use unbounded but this is not something you can enforce since they are the same type.

**Comment by matteo-dinoia** [comment]
> > I do believe there is still to talk about this. I think not defining this could cause some drone to behave differntly based on which type of channel we use.
> 
> As I said before the only difference is that with bounded send might block if there is not enough space in the buffer, so it's likely better to use unbounded but this is not something you can enforce since they are the same type.

We can enforce by rules in the protocols

**Comment by matteo-dinoia** [comment]
> I would say just use unbounded and you are good to go. If you want to use bounded do it at your own risk, but know that this may cause problems. But since this is done by the network initializer the problems are only to that group so it's fine

Yeah that is why i think we should decide for one standard and force everyone to use it.

**Comment by DiCesareDaniele** [comment]
I think a better option is to specify that send should not be blocking (and that if this is not the case the working of the network/drone is not ensured) and let the group decide how they want to handle that. e.g. unbounded or bounded(big_number) or bounded(small_number) and pray that no deadlocks occur. This way every group drone can assume that send will not block and then it's going to be the buyer to ensure that as he prefers

**Comment by matteo-dinoia** [comment]
That doesn't sound like a good idea when we can have a working code by enforcing it.

**Comment by Suge42** [comment]
Yea could be useful to vote on this, because if a drone was made for unbounded channels, and is applied on a network with bounded ones, based on the implementation it might send the wrong error (Like if I try to send to a full channel, I might get the same error I would for a crushed one or stuff like that idk)

**Comment by matteo-dinoia** [comment]
Voted for unbounded. Please create a PR
