### ISSUE TITLE
flood_id: randomly or ...?

### ISSUE THREAD

**Issue by RickyBenevelli** [WGL-2024/WGL_repo_2024#93]
How is the`flood_id` decided? Is the simulation controller to assign it? If it is taken randomly could collisions occur (yes)? Do we want to handle them or do we remain aware of them but adopt the [ostrich algorithm](https://en.wikipedia.org/wiki/Ostrich_algorithm)?

**Comment by matteo-dinoia** [comment]
We should decide something:

best idea is something like concatenation (as byte) of nodeId + sequential and/or random number

**Comment by DiCesareDaniele** [comment]
> We should decide something.
> 
> I think the best idea is something like concatenation (as byte) of nodeId + sequential and/or random number.
> 
> Or I guess just client defined and the drone also use the source of the packet to decide if the flood was already seen.

I prefer the second solution

**Comment by DiCesareDaniele** [comment]
Since this is a group defined part and we proposed a way to solve the problem please close this issue to not cloug up the Issues tab
